services:
  db:
    image: postgres:latest
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./my_app_logs:/app/logs
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_logs:/var/log/nginx
      - ./static:/static
      - ./media:/media
    depends_on:
      - backend
    ports:
      - "80:80"
