version: '3.2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
